name: Create files from users.txt
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"
      - name: Create and remove files from Users.txt
        run: |
          if [ ! -d "SUB" ]; then
            mkdir SUB
          fi
          while IFS=, read -r name value; do
            if [ "$value" -gt 0 ]; then
              touch "SUB/REALY-$name"
            fi
          done < Users.txt
          for file in SUB/*; do
            filename=$(basename -- "$file")
            if ! grep -q "$filename" Users.txt; then
              rm "$file"
            fi
          done
      - name: Commit and push changes
        run: |
          git add SUB
          git commit -m "Add and remove SUB folder files"
          git push origin main
