name: Run Rozshomar

on:
   push:
    branches:
      - main
      
   schedule:
    - cron: '30 2 * * *'  # Runs every day at 2:30 UTC which is 6:00 AM in Iran (UTC+3:30)

jobs:
  run_telegram_message_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run Date_Modifier
        run: |
          python Scripts/Date_Modifier.py  
       
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files" || exit 0  # Exit successfully if there's nothing to commit
          git push --force
