name: Rozshomar
on:
  schedule:
    - cron: '10 20 * * *'
jobs:
  update-users:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Update Users.txt
        run: |
          declare -a users
          while IFS= read -r line; do
            users+=("$line")
          done < Users.txt
          > Users.tmp
          for user in "${users[@]}"; do
            name=$(echo "$user" | cut -d',' -f1)
            date=$(echo "$user" | cut -d',' -f2)
            username=$(echo "$user" | cut -d',' -f3)
            new_date=$((date-1))
            if [ $new_date -ge -5 ]; then
              echo "$name, $new_date, $username" >> Users.tmp
            fi
          done
          mv Users.tmp Users.txt
      - name: Set up git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Commit changes
        run: |
          git add Users.txt
          git commit -m "Update Users.txt"
          git push origin main
