name: Create files from users.txt
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"
      - name: Remove files from SUB folder
        run: |
          if [ -d "SUB" ]; then
            rm -rf SUB/*
          fi
      - name: Create and copy files from users.txt
        run: |
          if [ ! -d "SUB" ]; then
            mkdir SUB
          fi
          while IFS=, read -r name value; do
            if [ "$value" -gt 0 ]; then
              cp Reality-1 "SUB/REALY-$name"
            fi
          done < Users.txt
      - name: Commit and push changes
        run: |
          git add SUB
          git commit -m "Add and copy SUB folder files"
          git push origin main
